[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"
pre-build = ["export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y libgpgme-dev libgpg-error-dev libdbus-1-dev pkg-config"]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
pre-build = ["dpkg --add-architecture arm64 && export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y libgpgme-dev:arm64 libgpg-error-dev:arm64 libdbus-1-dev:arm64 pkg-config"]
