[target.x86_64-unknown-linux-gnu]
pre-build = ["export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y libgpgme-dev libgpg-error-dev libdbus-1-dev"]

[target.aarch64-unknown-linux-gnu]
pre-build = ["dpkg --add-architecture arm64 && export DEBIAN_FRONTEND=noninteractive && apt-get update -y && apt-get install -y libgpgme-dev:arm64 libgpg-error-dev:arm64 libdbus-1-dev:arm64"]
